import { Nunito } from 'next/font/google';
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";
import Banner from "@/components/banner";
import WaitlistSection from "@/components/waitlistSection";
import Hero from "@/components/hero";
import ProductCarousel from '@/components/productCarousal';
import FeaturesCarousel from '@/components/featureCarousal';

const nunito = Nunito({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata = {
  title: "Coming soon - Sliq-pay",
  description: "Generated by Sliq-pay",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} antialiased`}
      >
        <Header />
        <Hero
          frontImg="/image/heroFrontImage.png"
          bgImg="/image/backgroundLayer.png"
          bgImgHover="/image/heroHoverBackgroundlayer.png"
        >
          <div className=" absolute top-[120px] left-0 w-full px-4 flex flex-col items-start text-left md:items-center md:text-center z-20">

            <h1
              className="leading-[1.20] text-[40px] md:text-[88px] text-[#0C1523] mb-2 md:mb-4 font-bold flex flex-wrap items-center"
              style={{ fontFamily: 'Malinton' }}
            >
              Money,
              <br className="md:hidden" />
              {' '}
              <span className="flex items-center md:ml-3 gap-2">
                 set free
                <img src="/svg/Stars.png" alt="stars" className="w-[32px] h-[34px] md:w-[90px] md:h-[90px]" />
              </span>
            </h1>
            <p
              className=" relative text-left md:left-[350px] md:top-[-35px] text-base text-[16px] h-[48px] text-[#3D444F] w-[270px] md:w-[206px]"
              style={{ fontFamily: 'Nunito' }}
            >
              Pay anyone in the world instantly, with a click.
            </p>
          </div>
        </Hero>
        <FeaturesCarousel />
        <Banner />
        <ProductCarousel />
        <WaitlistSection />
        <Footer />
      </body>
    </html>
  );
}
